<?php

return [
    'goa' => [
        'title' => 'Goa',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-goa',
        'images' => [
            'assets/img/work/images_sorted/goa/1.jpg',
            'assets/img/work/images_sorted/goa/2.jpg',
            'assets/img/work/images_sorted/goa/3.jpg',
            'assets/img/work/images_sorted/goa/4.jpg',
            'assets/img/work/images_sorted/goa/5.jpg',
            'assets/img/work/images_sorted/goa/6.jpg',
            'assets/img/work/images_sorted/goa/7.jpg',
            'assets/img/work/images_sorted/goa/8.jpg',
            'assets/img/work/images_sorted/goa/9.jpg',
            'assets/img/work/images_sorted/goa/10.jpg',
        ],
    ],
    'dubai' => [
        'title' => 'Dubai',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-dubai',
        'images' => [
            'assets/img/work/images_sorted/dubai/16.jpg',
            'assets/img/work/images_sorted/dubai/17.jpg',
            'assets/img/work/images_sorted/dubai/18.jpg',
            'assets/img/work/images_sorted/dubai/19.jpg',
            'assets/img/work/images_sorted/dubai/20.jpg',
            'assets/img/work/images_sorted/dubai/21.jpg',
            'assets/img/work/images_sorted/dubai/65.jpg',
            'assets/img/work/images_sorted/dubai/22.jpg',
            'assets/img/work/images_sorted/dubai/23.jpg',
            'assets/img/work/images_sorted/dubai/24.jpg',
            'assets/img/work/images_sorted/dubai/25.jpg',
            'assets/img/work/images_sorted/dubai/26.jpg',
            'assets/img/work/images_sorted/dubai/62.jpg',
        ],
    ],
    'kerela' => [
        'title' => 'Kerela',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-kerela',
        'images' => [
            'assets/img/work/images_sorted/kerela/47.png',
            'assets/img/work/images_sorted/kerela/49.jpg',
            'assets/img/work/images_sorted/kerela/50.png',
            'assets/img/work/images_sorted/kerela/52.jpg',
            'assets/img/work/images_sorted/kerela/53.png',
            'assets/img/work/images_sorted/kerela/54.png',
            'assets/img/work/images_sorted/kerela/55.png',
        ],
    ],

    'karjat' => [
        'title' => 'Karjat',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-karjat',
        'images' => [
            'assets/img/work/images_sorted/karjat/63.jpg',
            'assets/img/work/images_sorted/karjat/64.jpg',
            'assets/img/work/images_sorted/karjat/67.jpg',
            'assets/img/work/images_sorted/karjat/68.jpg',
            'assets/img/work/images_sorted/karjat/69.jpg',
            'assets/img/work/images_sorted/karjat/70.jpg',
            'assets/img/work/images_sorted/karjat/71.jpg',
            'assets/img/work/images_sorted/karjat/72.jpg',
            'assets/img/work/images_sorted/karjat/73.jpg',
            'assets/img/work/images_sorted/karjat/74.jpg',
            'assets/img/work/images_sorted/karjat/75.jpg',
            'assets/img/work/images_sorted/karjat/76.jpg',
            'assets/img/work/images_sorted/karjat/77.jpg',
            'assets/img/work/images_sorted/karjat/78.jpg',
        ],
    ],

    'vapi' => [
        'title' => 'vapi',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-vapi',
        'images' => [
            'assets/img/work/images_sorted/vapi/56.jpg',
            'assets/img/work/images_sorted/vapi/57.jpg',
            'assets/img/work/images_sorted/vapi/58.jpg',
            'assets/img/work/images_sorted/vapi/59.jpg',
            'assets/img/work/images_sorted/vapi/60.jpg',
            'assets/img/work/images_sorted/vapi/61.jpg',
            'assets/img/work/images_sorted/vapi/79.jpg',
            'assets/img/work/images_sorted/vapi/80.jpg',
            'assets/img/work/images_sorted/vapi/81.jpg',
        ],
    ],

    'satara' => [
        'title' => 'satara',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-satara',
        'images' => [
            'assets/img/work/images_sorted/satara/27.jpg',
            'assets/img/work/images_sorted/satara/28.jpg',
            'assets/img/work/images_sorted/satara/29.jpg',
            'assets/img/work/images_sorted/satara/30.jpg',
            'assets/img/work/images_sorted/satara/31.jpg',
            'assets/img/work/images_sorted/satara/32.jpg',
            'assets/img/work/images_sorted/satara/33.jpg',
        ],
    ],

    'jaipur' => [
        'title' => 'jaipur',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-jaipur',
        'images' => [
            'assets/img/work/images_sorted/jaipur/DSC00205.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00208.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00213.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00499.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00225.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00227.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00239.jpg',
            'assets/img/work/images_sorted/jaipur/DSC00511.jpg',
        ],
    ],

    'location-hub-1' => [
        'title' => 'Location Hub',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-location-hub-1',
        'images' => [
            'assets/img/work/images_sorted/location-hub-1/11.jpg',
            'assets/img/work/images_sorted/location-hub-1/12.jpg',
            'assets/img/work/images_sorted/location-hub-1/13.jpg',
            'assets/img/work/images_sorted/location-hub-1/14.jpg',
            'assets/img/work/images_sorted/location-hub-1/15.jpg',
        ],
    ],

    'location-hub-2' => [
        'title' => 'Location Hub',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-location-hub-2',
        'images' => [
            'assets/img/work/images_sorted/location-hub-2/34 .jpg',
            'assets/img/work/images_sorted/location-hub-2/34.jpg',
            'assets/img/work/images_sorted/location-hub-2/35.jpg',
            'assets/img/work/images_sorted/location-hub-2/36.jpg',
            'assets/img/work/images_sorted/location-hub-2/37.jpg',
            'assets/img/work/images_sorted/location-hub-2/38.jpg',
            'assets/img/work/images_sorted/location-hub-2/40.jpg',
            'assets/img/work/images_sorted/location-hub-2/41.jpg',
            'assets/img/work/images_sorted/location-hub-2/43.jpg',
            'assets/img/work/images_sorted/location-hub-2/44.jpg',
            'assets/img/work/images_sorted/location-hub-2/46.jpg',
        ],
    ],
    'jawai' => [
        'title' => 'Jawai',
        'subtitle' => 'VICKYGRAPHY.IN',
        'description' => 'Discover a showcase of our creative journey',
        'gallery_key' => 'gallery-jawai',
        'images' => [
            'assets/img/work/images_sorted/jawai/DSC00499.jpg',
            'assets/img/work/images_sorted/jawai/DSC00511.jpg',
            'assets/img/work/images_sorted/jawai/RAJ05411.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06014 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06165 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06294 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06320 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06353 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06361 copy.jpg',
            'assets/img/work/images_sorted/jawai/RAJ06787 copy.jpg',
        ],
    ],

];
